CBG-1468: Implement Mark phase of attachment compaction
couchbase/sync_gateway pull request #5287
Opened 2021-10-07 18:54 UTC by JRascagneres

CBG-1468

- PR for Mark phase of attachment compaction work
- Adds a SetXattr function allowing only an xattr to be updated without the additional work of adding body hash and cas.

## Dependencies
- [x] https://github.com/couchbase/sg-bucket/pull/66
- [x] https://github.com/couchbaselabs/walrus/pull/59
- [ ] https://github.com/couchbase/sync_gateway/pull/5293

## [Integration Tests](http://uberjenkins.sc.couchbase.com:8080/job/sync-gateway-integration/build?delay=0sec)
- [ ] `xattrs=true` http://uberjenkins.sc.couchbase.com:8080/job/sync-gateway-integration/???/
- [ ] `xattrs=false` http://uberjenkins.sc.couchbase.com:8080/job/sync-gateway-integration/???/

2021-10-08 21:15 UTC, adamcfraser requested changes
General approach looks ok, some questions about the implementation details.

2021-10-08 21:15 UTC, adamcfraser commented on base/bucket_xattr.go
> +func (bucket *CouchbaseBucketGoCB) SubdocSetXattr(k string, xattrKey string, exp uint32, cas uint64, xv interface{}) (casOut uint64, err error) {
Generally 'Set' is used to describe non-cas-safe operations, and 'Replace' or 'WriteCas' for the type of operation you're doing here.

2021-10-08 21:15 UTC, adamcfraser commented on db/document.go
> +	hasXattr, body, syncXattr, userXattr, err := SplitOutComponentsFromFeed(data, dataType, userXattrKey)
I find this change makes UnmarshalDocumentSyncDataFromFeed quite a bit harder to follow (error handling is obscured, 'hasXattr' is vague when there are sync, user, and any other xattrs possible).  More generally I'm not convinced that `SplitOutComponentsFromFeed` adds significant value to what parseXattrStreamData already provides, and having callers check the datatype doesn't seem like that much extra work.

2021-10-08 21:15 UTC, adamcfraser commented on db/document.go
> +func UnmarshalDocumentFromFeed(docid string, cas uint64, data []byte, dataType uint8, userXattrKey string) (doc *Document, err error) {
I'm fine with UnmarshalDocumentFromFeed as a helper function, but as mentioned above, I think it's clearer if you just do the dataType check here.

2021-10-08 21:15 UTC, adamcfraser commented on db/document.go
> +	if err != nil {
I usually skip the error check if the only thing we're doing afterward is return.  Can just switch to returning on line 467 and 469.

2021-10-08 21:15 UTC, adamcfraser commented on db/attachment_compaction.go
> +		if strings.HasPrefix(string(event.Key), "_") {
Our criteria for importing docs is `strings.HasPrefix(key, base.SyncPrefix)` - I think we should be using the same here.

We also want to return `true` in this case - we can consider this document as processed, and allow the DCP client to update the stream metadata accordingly.

2021-10-08 21:15 UTC, adamcfraser commented on db/attachment_compaction.go
> +			return false
Should this log a warning, or possibly have the process track the number of such documents encountered and report in its status?  

Here (and in all other cases we're returning false), review whether we actually want to avoid persisting a DCP checkpoint based on this mutation.  I think the answer is generally no, and we should return true.

2021-10-08 21:15 UTC, adamcfraser commented on db/attachment_compaction.go
> +				return false
If we hit an error with a single leaf, should we continue and process the other leaves? 

On the other hand, if you think this should be treated as a fatal error for the compaction process, you need a way to stop the process - returning false alone isn't going to do that.

2021-10-08 21:15 UTC, adamcfraser commented on db/attachment_compaction.go
> +				_, err = db.Bucket.WriteXattrUpdate(attKey, "_sync", func(xattr []byte) (updatedXattr []byte, err error) {
It seems like it would be common for conflicting leaf revisions to contain references to the same attachment.  I feel like you should be building a slice of all V1 attachments associated with the document, then iterating over that set once to stamp the compaction ID.

2021-10-08 21:15 UTC, adamcfraser commented on db/attachment_compaction.go
> +					base.DebugfCtx(db.Ctx, base.KeyAll, "[%s] Failed to mark attachment %s from doc %s rev %s with attachment docID %s. Err: %v", compactionLoggingID, attID, event.Key, leafRevision, attKey, err)
If we're killing the process, I assume we can also exit the callback here (definitely returning false this time, so that the compaction process could be retried in the case of transient server issues).

2021-10-08 21:15 UTC, adamcfraser commented on db/attachment_compaction.go
> +		return false
Why are we returning false here?

2021-10-09 01:29 UTC, JRascagneres commented on base/bucket_xattr.go
> +func (bucket *CouchbaseBucketGoCB) SubdocSetXattr(k string, xattrKey string, exp uint32, cas uint64, xv interface{}) (casOut uint64, err error) {
Swapping it out for an actual set now anyway without cas - no need for this with the setting of the xattr on the attachment.

2021-10-09 01:37 UTC, JRascagneres commented on db/attachment_compaction.go
> +		return false
To be honest I wasn't entirely sure what this was doing and just copied false from the test you had written. I think I understand that now so will go over it.

2021-10-09 02:04 UTC, JRascagneres commented on db/document.go
> +	hasXattr, body, syncXattr, userXattr, err := SplitOutComponentsFromFeed(data, dataType, userXattrKey)
Not sure I agree with this. Perhaps we should rename the `hasXattr` but otherwise I think this makes it easier to read to be honest. It adds some duplication.

Its not too much duplication or change though so I'm okay to be convinced otherwise. I'll switch it though if you think it makes it hard to read.

2021-10-13 05:00 UTC, adamcfraser commented on db/attachment_compaction.go
> +	<-doneChan
Should this be in a select to be able to react to a user stopping the compact via REST API?  Or is that work still pending?

2021-10-13 09:58 UTC, JRascagneres commented on db/attachment_compaction.go
> +	<-doneChan
Guessing I would've noticed this once I got around to the REST API work but makes sense to do this now :P

2021-10-14 18:58 UTC, adamcfraser commented on manifest/default.xml
> +  <project name="walrus" path="godeps/src/github.com/couchbaselabs/walrus" remote="couchbaselabs" revision="CBG-1468"/>
```suggestion
  <project name="walrus" path="godeps/src/github.com/couchbaselabs/walrus" remote="couchbaselabs" revision="a5872ff542ba9cf0452528bdbe7ec3f7e90e73d0"/>
```

2021-10-14 18:58 UTC, adamcfraser commented on manifest/default.xml
> +  <project name="sg-bucket" path="godeps/src/github.com/couchbase/sg-bucket" remote="couchbase" revision="CBG-1468"/>
```suggestion
  <project name="sg-bucket" path="godeps/src/github.com/couchbase/sg-bucket" remote="couchbase" revision="1972e5eab603e22c8be5e75cffc6f78de4a8b70c"/>
```

2021-10-14 18:59 UTC, adamcfraser submitted a review, later dismissed

2021-10-14 21:08 UTC, adamcfraser approved these changes

2021-10-14 21:09 UTC, merged