CBG-1469: Attachment compaction Sweep
couchbase/sync_gateway pull request #5290
Opened 2021-10-12 18:28 UTC by JRascagneres

CBG-1469

Implements the sweep phase of the attachment cleanup, deleting any attachments which are not marked with the same ID as the current attachment cleanup phase.

## Dependencies
- [x] https://github.com/couchbase/sync_gateway/pull/5287

## [Integration Tests](http://uberjenkins.sc.couchbase.com:8080/job/sync-gateway-integration/build?delay=0sec)
- [ ] `xattrs=true` http://uberjenkins.sc.couchbase.com:8080/job/sync-gateway-integration/???/
- [ ] `xattrs=false` http://uberjenkins.sc.couchbase.com:8080/job/sync-gateway-integration/???/

2021-10-13 06:29 UTC, adamcfraser requested changes

2021-10-13 06:29 UTC, adamcfraser commented on db/attachment_compaction.go
> +			_, xattr, _, err := parseXattrStreamData(base.SyncXattrName, "", event.Value)
I think we should use something other than _sync for the xattr name.

2021-10-13 06:29 UTC, adamcfraser commented on db/attachment_compaction.go
> +				}
Since we're doing a set in the mark phase, what do we want to do if there's a mismatch in compactionID?  Deleting the attachment doesn't seem appropriate if another compaction has somehow been started and overwritten the previous ID.

2021-10-13 06:29 UTC, adamcfraser commented on db/attachment_compaction.go
> +		err := db.Bucket.Delete(string(event.Key))
I don't think we have a use case for concurrent update, but doing a CAS-safe delete still seems prudent here.

2021-10-13 10:40 UTC, JRascagneres commented on db/attachment_compaction.go
> +		err := db.Bucket.Delete(string(event.Key))
Yeah that seems fair, can swap this out for `Remove`

2021-10-13 11:00 UTC, JRascagneres commented on db/attachment_compaction.go
> +				}
If there is a mismatch in compactionID pretty sure we do want to still delete it. What happens if there has been a previous run that marked it but now it has been removed from the doc it was attached to? Its not going to lose that xattr with the previous mark ID. 
I think we just need to be careful about not allowing two runs at the same time. Storing a compaction ID / status in the bucket for persistence should avoid this scenario.

2021-10-13 16:16 UTC, JRascagneres commented on db/attachment_compaction.go
> +			_, xattr, _, err := parseXattrStreamData(base.SyncXattrName, "", event.Value)
_sync:compact

2021-10-14 21:53 UTC, adamcfraser approved these changes

2021-10-14 21:53 UTC, merged