CBG-1755: Handle multiple compaction IDs
couchbase/sync_gateway pull request #5309
Opened 2021-10-25 19:14 UTC by JRascagneres

CBG-1755

- Switch to storing multiple compaction IDs in an xattr instead of just one --> Have a map with compactionID - timestamp
- Mark adds a compactionID with subdoc op
- Sweep reads the compactionIDs and does a basic check if the current running compactionID is present in the map
- Adds an additional phase which does a 'cleanup':
	- Deletes the current running compactionID from the map
	- If any other runs are more than 30 days old we also delete those (can occur if an earlier cleanup phase fails)

- Adds RemoveXattr which does a cas safe subdoc delete operation
- Adds DeleteXattr which does a straight delete operation with no cas check

## Dependencies
- [x] https://github.com/couchbaselabs/walrus/pull/60
- [x] https://github.com/couchbase/sg-bucket/pull/67

## Integration Tests
- [x] `xattrs=true` http://uberjenkins.sc.couchbase.com:8080/job/sync-gateway-integration/1319/
- [x] `xattrs=false` http://uberjenkins.sc.couchbase.com:8080/job/sync-gateway-integration/1313/

2021-10-26 22:44 UTC, adamcfraser requested changes

2021-10-26 22:44 UTC, adamcfraser commented on base/collection_xattr_common.go
> +		if errors.Is(err, gocb.ErrCasMismatch) {
The common wrappers in collection_xattr_common shouldn't have any gocb version-specific code, including error handling.  Could use IsCasMismatch here, but since we're just returning the error anyway, I think we can just omit this check and have RemoveXattr return the underlying error, so that callers could check for IsCasMismatch.

If you really think we need to return a typed error here, I think it should be a new ErrCasMismatch error.  ErrCasFailureShouldRetry has specific meaning for the WriteUpdate operations.  And any new error should be added to IsCasMismatch to ensure it continues working as expected.

2021-10-26 22:44 UTC, adamcfraser commented on db/attachment_compaction.go
> +		if event.DataType&base.MemcachedDataTypeXattr != 0 {
Maybe exit early in for non-xattr data types to reduce nesting?

2021-10-26 22:44 UTC, adamcfraser commented on db/attachment_compaction.go
> +				var syncData map[string]interface{}
syncData is a confusing name for this variable, since it's not sync metadata.

2021-10-26 22:44 UTC, adamcfraser commented on db/attachment_compaction.go
> +					base.WarnfCtx(db.Ctx, "[%s] Failed to unmarshal xattr data: %v", compactionLoggingID, err)
```suggestion
					base.WarnfCtx(db.Ctx, "[%s] Failed to unmarshal attachment comppaction xattr: %v", compactionLoggingID, err)
```

2021-10-26 22:44 UTC, adamcfraser commented on db/attachment_compaction.go
> +				compactIDSyncMap, ok := compactIDSync.(map[string]interface{})
Can we define a struct for the attachment compaction metadata and unmarshal to that in the first place?  I think it would simplify this code and also make it easier to see what's going on.

2021-10-26 22:44 UTC, adamcfraser commented on db/attachment_compaction.go
> +					err = db.Bucket.DeleteXattr(docID, getCompactionIDSubDocPath(compactID))
Can we avoid multiple kv ops when deleting multiple compaction IDs?

2021-10-27 13:48 UTC, JRascagneres commented on db/attachment_compaction.go
> +					err = db.Bucket.DeleteXattr(docID, getCompactionIDSubDocPath(compactID))
Yeah thats valid, have swapped DeleteXattr to DeleteXattrs and added an additional underlying subdoc op which allows multiple paths to be provided.

2021-10-28 16:29 UTC, adamcfraser reviewed
Looks good - just need to update manifest.

2021-10-28 16:29 UTC, adamcfraser commented on base/bucket_xattr.go
> +func (bucket *CouchbaseBucketGoCB) DeleteXattrs(k string, xattrKeys ...string) (err error) {
I think we may want to revisit the naming of these functions (as well as some existing functions) if we're passing a full path as 'xattrKey'.  The previous subdoc operations treated xattrKey as the name of the xattr, but the underlying implementation may support passing in a full path in some cases.  Not critical for this PR, will file an enhancement ticket.

2021-10-29 10:36 UTC, bbrks approved these changes

2021-10-29 12:27 UTC, merged