CBG-1760: Error upfront if logFilePath is unwritable
couchbase/sync_gateway pull request #5312
Opened 2021-10-26 18:43 UTC by IsaacLambat

CBG-1760

- SGW refuses to start if the log_file_path set is not writeable (eg. read-only, insufficient perms)
- Unit tested (non-Windows only due to https://github.com/golang/go/issues/35042 and other tests skip Windows when testing file/directory read-only perms)

## [Integration Tests](http://uberjenkins.sc.couchbase.com:8080/job/sync-gateway-integration/build?delay=0sec)
- [x] `xattrs=true` http://uberjenkins.sc.couchbase.com:8080/job/sync-gateway-integration/1​30​8

2021-10-26 18:51 UTC, bbrks requested changes

2021-10-26 18:51 UTC, bbrks commented on base/logging_config.go
> +	}
This seems a bit hacky to check for writability. Why not `os.Stat()` and `Perm`?

2021-10-27 10:23 UTC, IsaacLambat commented on base/logging_config.go
> +	}
As discussed, going to continue creating the file to check the permissions.

2021-10-28 12:23 UTC, bbrks reviewed
Just updates to comments, otherwise LGTM

2021-10-28 12:23 UTC, bbrks commented on base/logging_config.go
> +	_ = os.Remove(writeCheckFilePath)
```suggestion
	// best effort cleanup, but if we don't manage to remove it, WriteFile will overwrite on the next startup and try to remove again
	_ = os.Remove(writeCheckFilePath)
```

2021-10-28 12:23 UTC, bbrks commented on base/logging_config.go
> +	// Make temporary file to check if the log file path is writable
```suggestion
	// Make temporary empty file to check if the log file path is writable
```

2021-10-28 13:02 UTC, merged

2021-10-28 13:02 UTC, bbrks approved these changes