CBG-1765: Added GoCB v2 values to GetGoCBConnString
couchbase/sync_gateway pull request #5314
Opened 2021-10-27 17:25 UTC by IsaacLambat

CBG-1765

- GetGoCBConnString now builds the different connection strings depending on if using GoCB v1 or v2 (based on the BucketSpec.CouchbaseDriver)
- Added GoCB v2 connection string test

## [Integration Tests](http://uberjenkins.sc.couchbase.com:8080/job/sync-gateway-integration/build?delay=0sec)
- [x] `xattrs=true` http://uberjenkins.sc.couchbase.com:8080/job/sync-gateway-integration/1314

2021-10-27 18:00 UTC, JRascagneres requested changes
I think this looks good, one comment though.

2021-10-27 18:00 UTC, JRascagneres commented on base/bucket.go
> +	poolSizeFromConnStr := connValues.Get("kv_pool_size")
Given kv pool size hasn't changes (and that its a fairly large portion of the implementation can we pull that out and still perform that in `GetGoCBConnString`?

2021-10-27 18:00 UTC, JRascagneres commented on base/bucket.go
> +	poolSizeFromConnStr := connValues.Get("kv_pool_size")
As above

2021-10-28 10:03 UTC, JRascagneres submitted a review, later dismissed

2021-10-28 13:00 UTC, bbrks approved these changes

2021-10-28 13:00 UTC, merged